### ISSUE TITLE
ioerror 

### ISSUE THREAD

**Issue by gup-abhi** [Ori226/p300_lstm#3]
start subject:gcd
Traceback (most recent call last):
  File "run_multi_subject_experiment.py", line 243, in <module>
    main()
  File "run_multi_subject_experiment.py", line 237, in main
    model=model)
  File "run_multi_subject_experiment.py", line 150, in train_and_evaluate
    cross_validation_iter=cross_validation_iter)
  File "run_multi_subject_experiment.py", line 86, in prepare_data_for_experiment
    create_data_rep_training_public(file_name, -200, 800, downsample_params=downsample_params)
  File "C:\Users\Abhishek\Desktop\Project\p300_lstm-master\utils.py", line 160, in create_data_rep_training_public
    data_from_file = readCompleteMatFile(file_name)
  File "C:\Users\Abhishek\Desktop\Project\p300_lstm-master\utils.py", line 112, in readCompleteMatFile
    res = sio.loadmat(file_path)
  File "C:\Users\Abhishek\Anaconda3\lib\site-packages\scipy\io\matlab\mio.py", line 142, in loadmat
    matfile_dict = MR.get_variables(variable_names)
  File "C:\Users\Abhishek\Anaconda3\lib\site-packages\scipy\io\matlab\mio5.py", line 292, in get_variables
    res = self.read_var_array(hdr, process)
  File "C:\Users\Abhishek\Anaconda3\lib\site-packages\scipy\io\matlab\mio5.py", line 252, in read_var_array
    return self._matrix_reader.array_from_header(header, process)
  File "mio5_utils.pyx", line 675, in scipy.io.matlab.mio5_utils.VarReader5.array_from_header
  File "mio5_utils.pyx", line 721, in scipy.io.matlab.mio5_utils.VarReader5.array_from_header
  File "mio5_utils.pyx", line 894, in scipy.io.matlab.mio5_utils.VarReader5.read_cells
  File "mio5_utils.pyx", line 673, in scipy.io.matlab.mio5_utils.VarReader5.read_mi_matrix
  File "mio5_utils.pyx", line 723, in scipy.io.matlab.mio5_utils.VarReader5.array_from_header
  File "mio5_utils.pyx", line 969, in scipy.io.matlab.mio5_utils.VarReader5.read_struct
  File "mio5_utils.pyx", line 673, in scipy.io.matlab.mio5_utils.VarReader5.read_mi_matrix
  File "mio5_utils.pyx", line 705, in scipy.io.matlab.mio5_utils.VarReader5.array_from_header
  File "mio5_utils.pyx", line 778, in scipy.io.matlab.mio5_utils.VarReader5.read_real_complex
  File "mio5_utils.pyx", line 450, in scipy.io.matlab.mio5_utils.VarReader5.read_numeric
  File "mio5_utils.pyx", line 355, in scipy.io.matlab.mio5_utils.VarReader5.read_element
  File "streams.pyx", line 195, in scipy.io.matlab.streams.ZlibInputStream.read_string
  File "streams.pyx", line 188, in scipy.io.matlab.streams.ZlibInputStream.read_into
OSError: could not read bytes

Please help!!

**Comment by gup-abhi** [comment]
use h5py library instead of scipy for loadmat file.
