### ISSUE TITLE
keyerror

### ISSUE THREAD

**Issue by gup-abhi** [Ori226/p300_lstm#4]
Traceback (most recent call last):
  File "run_single_subject_for_test.py", line 54, in <module>
    main()
  File "run_single_subject_for_test.py", line 47, in main
    model=model)
  File "C:\Users\Abhishek\Desktop\Project\p300_lstm-master\run_multi_subject_experiment.py", line 150, in train_and_evaluate
    cross_validation_iter=cross_validation_iter)
  File "C:\Users\Abhishek\Desktop\Project\p300_lstm-master\run_multi_subject_experiment.py", line 86, in prepare_data_for_experiment
    create_data_rep_training_public(file_name, -200, 800, downsample_params=downsample_params)
  File "C:\Users\Abhishek\Desktop\Project\p300_lstm-master\utils.py", line 161, in create_data_rep_training_public
    data_from_file = readCompleteMatFile(file_name)
  File "C:\Users\Abhishek\Desktop\Project\p300_lstm-master\utils.py", line 115, in readCompleteMatFile
    all_relevant_channels, channels_names, marker_positions, target = extractBasicData(res)
  File "C:\Users\Abhishek\Desktop\Project\p300_lstm-master\utils.py", line 47, in extractBasicData
    set_1 = [x[0] for x in res['nfo']['clab'][0][0][0]]
KeyError: 'nfo'

**Comment by gup-abhi** [comment]
Please check the utils.py file for error. Please help as soon as possible.

**Comment by Ori226** [comment]
Hi @ilovechelsea . The main problem is that the original website where the files were located is down. I'm trying to contact the database owner to understand if how we can solve it. Meanwhile, I have a copy of the original data set. If you'll send me you email, I can try to send it to you

**Comment by gup-abhi** [comment]
agabhishek20121998@gmail.com
Thanks it will be helpful

**Comment by gup-abhi** [comment]
Can you upload on google drive and share the link please for dataset

**Comment by gup-abhi** [comment]
Are going to send dataset or not please tell ?

**Comment by Ori226** [comment]
Hi @ilovechelsea . Looks like that if you'll try to use the original code now it will download the data. Sorry for the delay

**Comment by gup-abhi** [comment]
If put in the keras folder it works without downloading. So if you can share dataset that would be really helpful.
